### ISSUE TITLE
problem installing with composer.

### ISSUE THREAD

**Issue by AnwarQasem** [ivus/crudadminlte#1]
$ composer require ivus/crudadminlte
                                                                                         
[InvalidArgumentException]                                                                                                                         
Could not find package ivus/crudadminlte at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability                                                                                                                                                       

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [packages1] ... [packagesN]

**Comment by ivus** [comment]
Hi @AnwarQasem 

Thank you for your interest in my project. As this is my first package build, I was simply testing the composer install process last night and forgot to remove the package from my Packagist package.

I only started work on this project around 5 days ago so it is no where near ready for production.

If you'd like, I can notify you when it is ready, or perhaps you'd consider being a tester when it goes into beta. I do apologise if I have wasted any of your time. Thank you again.
